version: '3.8'

services:
  frontend:
    environment:
      NUXT_PUBLIC_API_URL: http://localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

  backend:
    environment:
      NODE_ENV: development
    command: dev-command-placeholder
