# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    bitrix24sdk.app.client_id: '%env(BITRIX24_PHP_SDK_APPLICATION_CLIENT_ID)%'
    bitrix24sdk.app.client_secret: '%env(BITRIX24_PHP_SDK_APPLICATION_CLIENT_SECRET)%'
    bitrix24sdk.app.scope: '%env(BITRIX24_PHP_SDK_APPLICATION_SCOPE)%'
    bitrix24sdk.app.local.domain: '%env(BITRIX24_PHP_SDK_LOCAL_APPLICATION_DOMAIN)%'
    # pass dev host to the application
    APPLICATION_HOST: '%env(NUXT_PUBLIC_API_URL)%'

    # JWT Authentication parameters
    jwt.secret: '%env(JWT_SECRET)%'
    jwt.ttl: 3600
    jwt.algorithm: '%env(JWT_ALGORITHM)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Bitrix24 SDK services
    Bitrix24\Lib\ApplicationInstallations\UseCase\Install\Handler:
        autowire: true
    Bitrix24\Lib\ApplicationInstallations\UseCase\OnAppInstall\Handler:
        autowire: true
    Bitrix24\Lib\Bitrix24Accounts\UseCase\RenewAuthToken\Handler:
        autowire: true
    Bitrix24\Lib\Services\Flusher:
        autowire: true

    Bitrix24\SDK\Services\RemoteEventsFactory:
        autowire: true
        factory: [ null, 'init' ]

    # Bitrix24 SDK repository bindings
    Bitrix24\SDK\Application\Contracts\Bitrix24Accounts\Repository\Bitrix24AccountRepositoryInterface:
        class: Bitrix24\Lib\Bitrix24Accounts\Infrastructure\Doctrine\Bitrix24AccountRepository
    Bitrix24\SDK\Application\Contracts\ApplicationInstallations\Repository\ApplicationInstallationRepositoryInterface:
        class: Bitrix24\Lib\ApplicationInstallations\Infrastructure\Doctrine\ApplicationInstallationRepository

    # Bitrix24 SDK event listeners
    App\Bitrix24Core\Bitrix24SdkEventListener:
        tags:
            - { name: kernel.event_listener, event: Bitrix24\SDK\Events\AuthTokenRenewedEvent, method: onAuthTokenRenewedEventListener }

    # JWT Authentication services
    App\Service\JwtService:
        arguments:
            $secret: '%jwt.secret%'
            $ttl: '%jwt.ttl%'
            $algorithm: '%jwt.algorithm%'

    App\EventListener\JwtAuthenticationListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 10 }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
